# Generated by Django 5.2 on 2025-04-29 09:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_order'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_line1', models.CharField(max_length=255)),
                ('address_line2', models.CharField(blank=True, max_length=255, null=True)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('postal_code', models.CharField(max_length=20)),
                ('is_default', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.profile')),
            ],
            options={
                'verbose_name_plural': 'Delivery Address Table',
            },
        ),
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PE', 'Chờ xử lý'), ('CO', 'Đã xác nhận'), ('PR', 'Đang chuẩn bị'), ('RP', 'Sẵn sàng lấy hàng'), ('PU', 'Đã lấy hàng'), ('OW', 'Đang giao hàng'), ('DE', 'Đã giao hàng'), ('CA', 'Đã hủy')], default='PE', max_length=2)),
                ('estimated_delivery_time', models.DateTimeField(blank=True, null=True)),
                ('actual_delivery_time', models.DateTimeField(blank=True, null=True)),
                ('delivery_notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='myapp.order')),
                ('delivery_address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.deliveryaddress')),
            ],
            options={
                'verbose_name_plural': 'Delivery Table',
            },
        ),
        migrations.CreateModel(
            name='DeliveryTracking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PE', 'Chờ xử lý'), ('CO', 'Đã xác nhận'), ('PR', 'Đang chuẩn bị'), ('RP', 'Sẵn sàng lấy hàng'), ('PU', 'Đã lấy hàng'), ('OW', 'Đang giao hàng'), ('DE', 'Đã giao hàng'), ('CA', 'Đã hủy')], max_length=2)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('delivery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracking_logs', to='myapp.delivery')),
            ],
            options={
                'verbose_name_plural': 'Delivery Tracking Table',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Shipper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_type', models.CharField(max_length=50)),
                ('vehicle_number', models.CharField(max_length=20)),
                ('license_number', models.CharField(max_length=50)),
                ('availability_status', models.BooleanField(default=True)),
                ('current_location', models.CharField(blank=True, max_length=255, null=True)),
                ('rating', models.FloatField(default=5.0)),
                ('total_deliveries', models.IntegerField(default=0)),
                ('joined_on', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Shipper Table',
            },
        ),
        migrations.AddField(
            model_name='delivery',
            name='shipper',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.shipper'),
        ),
    ]
