# Generated by Django 5.2 on 2025-05-10 04:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_restaurant_dish_restaurant'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveIntegerField(default=5)),
                ('comment', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.profile')),
                ('delivery', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='myapp.delivery')),
            ],
            options={
                'verbose_name_plural': 'Delivery Review Table',
            },
        ),
    ]
